kind = "web"
previewPath = "/"
title = "Nexora Labs"
version = "1.0.0"
id = "artifacts/nexora-labs"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22019

[services.development]
run = "pnpm --filter @workspace/nexora-labs run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexora-labs", "run", "build" ]
publicDir = "artifacts/nexora-labs/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22019"
BASE_PATH = "/"
